language: node_js

services:
  - docker

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/
addons:
  chrome: stable
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "stfsRk8QKfns8hqznhrVmaEN0jvisW3aGF16wKh9necbxU5YxmA4lyusGbgltqQrZbAA5w23u5g829thLEdQUYcZOWn2UciYAhCzz1YfP34Ac+RIztJ92gc1VauQ6cSuSZbQ/2kmpaLD3OgdG5AJjrJtlcHGNAal2y5JJk+O+gB5RddADiA2TqpvBYcMZTiSBgcfgTYVWgSANbtjTtcj62dLLeaVRT4FADk6jrukD363RKTnJnQ+xBz+STn2vyBs3OENznciXBc5o0tCsebO7DOQAnbHccyxaNEp+qK34tH1xfVY04opy0f0cJ6UUI9PmI6cwt7BNTupYLfPsBknlz8mEDOazR+aaxUGloJDpQZ5oqPYYOjNIj0SI3zTgxLUgZ5PHOmhf+j9Ld/LJM2U3QiulL65C/j7Y/GuOi+VzUTHh8mtnPP30k2Y4rh1SPaInJhtTqOeytU4y2/FSmD9N5JBY8CguoKz6RVjnoBxBySvC6MIob6CfJgYlXuc2tu+l6lHqokPaZemnKXc3ahWJlADTWH3CI1zyXINLj7KAv4GLmi64BMFehwqH41BQUVQL2dwGWwfGLVhJ0mMohPL5J/HG7c4WPpvtzxI5Xg9SeihqCWavz0o9/5z/+Fcc6BV/u0BPDkNDCG8OGAwWK/idbm2V3Iw5iMBRLt8ufkxJ+8="

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh

stages:
  - e2e-test

before_script:
  - make init

jobs:
  include:
    - stage: e2e-test
      name: "Run unit tests and e2e tests"
      if: type = cron OR type = pull_request
      script:
        - set -e
        - make sonar/js/jest-init
        - make unit-test
        - set +e
        - make component/test/e2e
        - npm run merge:coverage
        - echo '"start sonar checking..."' && echo -en 'travis_fold:start:script.build\\r'
        - make sonar/js
        - echo '"finished sonar check"' && echo -en 'travis_fold:end:script.build\\r'
      after_failure:
        - make travis-slack-reporter
        - docker logs grcuiapi
